CREATE TABLE IF NOT EXISTS produtos(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(300) NOT NULL DEFAULT '',
	estoque DECIMAL(9,3) NOT NULL DEFAULT 0,
	CONSTRAINT cp_produtos PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS clientes(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(300) NOT NULL DEFAULT '',
	CONSTRAINT cp_clientes PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS pedidos(
	id INT NOT NULL AUTO_INCREMENT,
	data DATE NOT NULL DEFAULT '0001-01-01', 
	cliente_id INT NOT NULL,
	cancelado TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT cp_pedidos PRIMARY KEY (id),
	CONSTRAINT ce_pedidos__cliente_id FOREIGN KEY (cliente_id) REFERENCES clientes(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS pedidos_itens(
	id INT NOT NULL AUTO_INCREMENT,
	pedido_id INT NOT NULL,
	produto_id INT NOT NULL,
	quantidade DECIMAL(9,3) NOT NULL DEFAULT 0,
	CONSTRAINT cp_pedidos_itens PRIMARY KEY (id),
	CONSTRAINT ce_pedidos_itens__pedido_id FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
	CONSTRAINT ce_pedidos_itens__produto_id FOREIGN KEY (produto_id) REFERENCES produtos(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
